name: Compile Library

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        idf_version:
          - "v5.1"
          - "v5.2"
          - "v5.3"
        target:
          - "esp32"
          - "esp32s3"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ESP-IDF example
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf_version }}
          target: ${{ matrix.target }}
          path: examples/espidf-basic
